server:
  port: 8082
  servlet:
    context-path: /knife-front-api
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    root: info

mybatis-plus:
  configuration:
    call-setters-on-nulls: true

